// Single source of truth for every third-party provider the platform knows about.
// The school-web UI renders from here; nothing about a provider is hardcoded in the frontend.
// Docs URLs were checked against vendor-owned pages on 2026-09-25. Where a vendor publishes
// no public API reference, `docs` is empty and `setupNote` says who to contact instead.

export type PlanTier = "basic" | "standard" | "premium";

export type ProviderCategory =
  | "accounting"
  | "payments"
  | "communication"
  | "attendance-hardware"
  | "transport"
  | "learning"
  | "finance"
  | "documents"
  | "compliance"
  | "storage";

export type ConnectionStatus =
  | "connected"
  | "pending"
  | "error"
  | "available"
  | "locked"
  | "not-offered";

export type CostModel = "one-time" | "metered" | "licence" | "included" | "commercial";

export interface IntegrationField {
  key: string;
  label: string;
  type: "text" | "secret" | "url" | "select";
  options?: string[];
  placeholder?: string;
  hint?: string;
  /** AES-encrypted into TenantIntegration.secrets; never returned by the API after save. */
  sensitive?: boolean;
  required?: boolean;
}

export interface DocLink {
  label: string;
  url: string;
}

export interface IntegrationProvider {
  id: string;
  name: string;
  vendor: string;
  category: ProviderCategory;
  summary: string;
  whoPays: string;
  costModel: CostModel;
  costNote: string;
  minPlan: PlanTier | "any";
  /** Who is allowed to type the credentials. A platform admin must not become a school's password vault. */
  setupOwner: "school_admin" | "super_admin" | "platform";
  builtIn?: boolean;
  offered?: boolean;
  notOfferedReason?: string;
  docs: DocLink[];
  setupNote?: string;
  fields: IntegrationField[];
}

export const PLAN_ORDER: Record<PlanTier, number> = { basic: 1, standard: 2, premium: 3 };

export const PLAN_LABEL: Record<PlanTier, string> = {
  basic: "Starter",
  standard: "Growth",
  premium: "Institution",
};

export const CATEGORY_LABEL: Record<ProviderCategory, string> = {
  accounting: "Accounting",
  payments: "Payments",
  communication: "Communication",
  "attendance-hardware": "Attendance hardware",
  transport: "Transport",
  learning: "Teaching",
  finance: "Fee financing",
  documents: "Documents",
  compliance: "Compliance",
  storage: "Storage",
};

export const COST_MODEL_LABEL: Record<CostModel, string> = {
  "one-time": "One-time setup",
  metered: "Metered per use",
  licence: "School's own licence",
  included: "Included in plan",
  commercial: "Business deal",
};

export const CONNECTION_STATUSES = [
  "connected",
  "pending",
  "error",
] as const satisfies readonly ConnectionStatus[];

export const PROVIDERS: IntegrationProvider[] = [
  {
    id: "tally",
    name: "TallyPrime",
    vendor: "Tally Solutions",
    category: "accounting",
    summary:
      "Push fee receipts, expenses and opening balances into the school's own accounting books.",
    whoPays: "School — it already owns its Tally licence",
    costModel: "licence",
    costNote: "No per-sync cost to us. One-time bridge build.",
    minPlan: "basic",
    setupOwner: "school_admin",
    docs: [
      { label: "Tally developer reference", url: "https://help.tallysolutions.com/developer-reference/" },
      { label: "Integration methods and technologies", url: "https://help.tallysolutions.com/integration-methods-and-technologies/" },
    ],
    setupNote:
      "There is no Tally cloud API. The XML/HTTP port listens on the school's own accounts machine (typically http://<tally-host>:9000), so reaching it needs an on-prem bridge or tunnel from that network. Budget the bridge, not just the request format.",
    fields: [
      { key: "company", label: "Tally company name", type: "text", placeholder: "Demo Academy FY 2026-27", required: true },
      { key: "host", label: "Tally server address", type: "text", placeholder: "192.168.1.20", hint: "LAN IP of the accounts machine, or the bridge host", required: true },
      { key: "port", label: "XML port", type: "text", placeholder: "9000" },
      { key: "bridgeToken", label: "Bridge token", type: "secret", hint: "Generated by the on-prem bridge", sensitive: true },
      { key: "ledgerMode", label: "Ledger mapping", type: "select", options: ["Auto-map by fee head", "Manual mapping table"] },
    ],
  },
  {
    id: "zoho-books",
    name: "Zoho Books",
    vendor: "Zoho",
    category: "accounting",
    summary: "Cloud ledger alternative to Tally for schools with no on-prem machine.",
    whoPays: "School — its own Zoho Books subscription",
    costModel: "licence",
    costNote: "API calls are free within Zoho's own quota.",
    minPlan: "standard",
    setupOwner: "school_admin",
    docs: [
      { label: "Books REST API v3 introduction", url: "https://www.zoho.com/books/api/v3/introduction/" },
      { label: "OAuth overview", url: "https://www.zoho.com/books/api/v3/oauth/" },
      { label: "Create a client (API console)", url: "https://api-console.zoho.com" },
    ],
    setupNote:
      "Indian organisations sit on the .in data centre (https://www.zohoapis.in/books/). Pick the wrong one and every call 404s with a token error, so keep data centre as an explicit field.",
    fields: [
      { key: "orgId", label: "Organisation ID", type: "text", placeholder: "4923xxxxxx81", required: true },
      { key: "clientId", label: "OAuth client ID", type: "text", required: true },
      { key: "clientSecret", label: "OAuth client secret", type: "secret", sensitive: true, required: true },
      { key: "dataCenter", label: "Data centre", type: "select", options: ["zoho.in (India)", "zoho.com (US)"] },
    ],
  },
  {
    id: "whatsapp",
    name: "WhatsApp Business",
    vendor: "Meta Cloud API via a BSP",
    category: "communication",
    summary: "Fee reminders, attendance alerts and notices on the channel parents actually read.",
    whoPays: "School — per-message, billed through your add-on",
    costModel: "metered",
    costNote: "Needs DLT registration + pre-approved templates before the first send.",
    minPlan: "standard",
    setupOwner: "school_admin",
    docs: [
      { label: "WhatsApp Cloud API — get started", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/get-started" },
      { label: "TRAI advice to senders (DLT)", url: "https://trai.gov.in/advice-to-senders" },
      { label: "Gupshup docs", url: "https://docs.gupshup.io/" },
      { label: "WATI API reference", url: "https://docs.wati.io/reference/introduction" },
      { label: "AiSensy API reference", url: "https://aisensy.com/tutorials/api-reference-docs" },
    ],
    setupNote:
      "Meta Business Portfolio verification and display-name / number approvals come before any message goes out, and most schools reach the Cloud API through a BSP contract. Never absorb per-message cost into a fixed plan.",
    fields: [
      { key: "bsp", label: "Business solution provider", type: "select", options: ["Gupshup", "WATI", "AiSensy", "Kaleyra"], required: true },
      { key: "waBusinessId", label: "WhatsApp business account ID", type: "text" },
      { key: "apiKey", label: "BSP API key", type: "secret", sensitive: true, required: true },
      { key: "dltEntity", label: "DLT principal entity ID", type: "text", hint: "TRAI registration, not a Meta field" },
    ],
  },
  {
    id: "sms",
    name: "SMS gateway",
    vendor: "MSG91 / Route Mobile",
    category: "communication",
    summary: "OTP fallback and the failsafe when WhatsApp or push doesn't land.",
    whoPays: "School — per SMS",
    costModel: "metered",
    costNote: "Same DLT template approval drag as WhatsApp.",
    minPlan: "basic",
    setupOwner: "school_admin",
    docs: [
      { label: "MSG91 Send SMS API", url: "https://docs.msg91.com/sms/send-sms" },
      { label: "MSG91 DLT registration in India", url: "https://msg91.com/help/dlt-registration-in-india" },
      { label: "Route Mobile developer hub", url: "https://developer.rmlconnect.net/" },
      { label: "TRAI advice to senders (DLT)", url: "https://trai.gov.in/advice-to-senders" },
    ],
    setupNote:
      "Principal Entity registration, header approval and content templates happen on each operator's DLT portal (Jio / Airtel / Vi / BSNL) with entity KYC. That is days of lead time, not an API call — don't promise a same-day go-live.",
    fields: [
      { key: "provider", label: "Provider", type: "select", options: ["MSG91", "Route Mobile", "Tata Communications"], required: true },
      { key: "senderId", label: "Registered sender ID", type: "text", placeholder: "ACDEMO", required: true },
      { key: "authKey", label: "API auth key", type: "secret", sensitive: true, required: true },
    ],
  },
  {
    id: "biometric",
    name: "Biometric / RFID devices",
    vendor: "eSSL · Matrix Comsec · ZKTeco",
    category: "attendance-hardware",
    summary: "Devices push punch records straight into attendance. No manual register entry.",
    whoPays: "School — buys its own devices",
    costModel: "one-time",
    costNote: "Inbound webhook. Zero per-punch cost forever.",
    minPlan: "standard",
    setupOwner: "school_admin",
    docs: [
      { label: "ZKTeco SDK downloads", url: "https://www.zkteco.com/en/SDK" },
      { label: "ZKTeco Standalone SDK (protocol)", url: "https://github.com/ZKTeco/Standalone-SDK" },
      { label: "ZKBio Time API", url: "https://www.zkteco.com/en/ZKBioTime_API" },
      { label: "eSSL software integration", url: "https://esslsecurity.com/software-integration" },
      { label: "Matrix Comsec device API wiki", url: "https://wiki.matrixcomsec.com/index.php?title=How_to_configure_Device_API%3F%3F" },
    ],
    setupNote:
      "Only ZKTeco publishes a usable public spec. eSSL and Matrix share their push-to-URL payload format on request through a channel partner — get it in writing before quoting. Note that essl.co.in is a different company (CAMS Biometrics) and explicitly disclaims affiliation.",
    fields: [
      { key: "brand", label: "Device brand", type: "select", options: ["eSSL", "Matrix Comsec", "ZKTeco"], required: true },
      { key: "serials", label: "Device serial numbers", type: "text", hint: "Comma separated, one per gate" },
      { key: "webhookSecret", label: "Push verification secret", type: "secret", sensitive: true, hint: "Shown once — the device sends it with every punch" },
    ],
  },
  {
    id: "bus-gps",
    name: "Live bus tracking",
    vendor: "Google Maps Platform / Mappls",
    category: "transport",
    summary: "Parents watch the bus; the school stops answering 'where is it' calls.",
    whoPays: "School — metered on map calls",
    costModel: "metered",
    costNote: "Pass the quota through as a paid add-on. Never absorb into Starter.",
    minPlan: "premium",
    setupOwner: "school_admin",
    docs: [
      { label: "Google Maps — get started", url: "https://developers.google.com/maps/get-started" },
      { label: "Routes API", url: "https://developers.google.com/maps/documentation/routes" },
      { label: "Fleet Engine", url: "https://developers.google.com/maps/documentation/mobility/fleet-engine" },
      { label: "Mappls developer portal", url: "https://about.mappls.com/api/" },
    ],
    setupNote:
      "Routes alone covers ETA and school-bus routing. Fleet Engine is the heavier product and needs a billed GCP project. Mappls is the India-native option with local PoI coverage.",
    fields: [
      { key: "mapsProvider", label: "Maps provider", type: "select", options: ["Google Maps Platform", "Mappls MapmyIndia"], required: true },
      { key: "mapsKey", label: "Maps API key", type: "secret", sensitive: true, required: true },
      { key: "trackers", label: "GPS tracker IMEIs", type: "text" },
      { key: "geofence", label: "Alert radius", type: "select", options: ["150 m", "300 m", "500 m"] },
    ],
  },
  {
    id: "video-classes",
    name: "Online classes",
    vendor: "100ms / self-hosted Jitsi",
    category: "learning",
    summary: "Virtual classrooms and PTMs inside the school's own branding.",
    whoPays: "School — per participant minute",
    costModel: "metered",
    costNote: "Jitsi self-host is the only zero-metro option, and it moves the cost onto our infra.",
    minPlan: "premium",
    setupOwner: "super_admin",
    docs: [
      { label: "100ms docs", url: "https://www.100ms.live/docs" },
      { label: "Jitsi self-hosting handbook", url: "https://jitsi.github.io/handbook/docs/devops-guide/" },
    ],
    setupNote:
      "Self-hosted Jitsi means owning JVB / jicofo / prosody plus TURN. The public meet.jit.si is rate limited — treat it as a demo, not a school's production room.",
    fields: [
      { key: "provider", label: "Provider", type: "select", options: ["100ms", "Jitsi (self-hosted)"], required: true },
      { key: "appId", label: "App ID", type: "text" },
      { key: "secret", label: "Signing secret", type: "secret", sensitive: true },
    ],
  },
  {
    id: "fee-financing",
    name: "Fee financing / EMI",
    vendor: "Intelys SmartE and similar",
    category: "finance",
    summary: "Parents pay fees in instalments; the school gets paid upfront by the lender.",
    whoPays: "Lender pays us a referral share; parent pays interest",
    costModel: "commercial",
    costNote: "Contract first, code second.",
    minPlan: "premium",
    setupOwner: "super_admin",
    docs: [],
    setupNote:
      "This is business development, not an integration. There is no public sandbox — a lender issues merchant credentials only after the agreement is signed.",
    fields: [
      { key: "partner", label: "Lender partner", type: "text", placeholder: "Intelys SmartE", required: true },
      { key: "merchantId", label: "Merchant ID", type: "text" },
      { key: "apiKey", label: "Partner API key", type: "secret", sensitive: true },
    ],
  },
  {
    id: "esign",
    name: "Document e-sign",
    vendor: "Digio / eMudhra",
    category: "documents",
    summary: "Admission forms and NDAs signed on a phone instead of printed and scanned.",
    whoPays: "School — per signed document",
    costModel: "metered",
    costNote: "Both vendors price per pack; resale at a marked-up per-document rate.",
    minPlan: "standard",
    setupOwner: "school_admin",
    docs: [
      { label: "Digio documentation", url: "https://documentation.digio.in/" },
      { label: "Digio eSign API", url: "https://documentation.digio.in/digisign/" },
      { label: "eMudhra emSigner REST API", url: "https://developers.emsigner.com/esignature-api.html" },
    ],
    setupNote:
      "Both are commercial subscriptions — sandbox credentials are issued after onboarding, so a school cannot self-serve this the way it can a gateway key.",
    fields: [
      { key: "provider", label: "Provider", type: "select", options: ["Digio", "eMudhra"], required: true },
      { key: "apiToken", label: "API token", type: "secret", sensitive: true, required: true },
      { key: "signerName", label: "Authorised signer", type: "text" },
    ],
  },
  {
    id: "payroll-statutory",
    name: "Payroll statutory (PF / ESI / TDS)",
    vendor: "No public API",
    category: "compliance",
    summary: "Challan generation and salary TDS for teaching staff.",
    whoPays: "—",
    costModel: "commercial",
    costNote: "EPFO and income-tax portals have no usable API. Would need a compliance vendor.",
    minPlan: "premium",
    setupOwner: "super_admin",
    offered: false,
    notOfferedReason: "No public API — would be a vendor purchase, not an integration.",
    docs: [],
    fields: [],
  },
  {
    id: "cbse-udise",
    name: "CBSE / UDISE+ reporting",
    vendor: "No public API",
    category: "compliance",
    summary: "Statutory school returns principals currently file by hand.",
    whoPays: "—",
    costModel: "commercial",
    costNote: "Manual portal entry only. Sellable as a prepared-file service.",
    minPlan: "premium",
    setupOwner: "super_admin",
    offered: false,
    notOfferedReason: "Government portals expose no API. We can prepare the file, not push it.",
    docs: [],
    fields: [],
  },
  {
    id: "razorpay",
    name: "Razorpay",
    vendor: "Built into the platform",
    category: "payments",
    summary: "Fee collection, refunds and B2C subscription billing.",
    whoPays: "School — gateway MDR per transaction",
    costModel: "included",
    costNote: "Already live. Per-school keys are on the roadmap, not per-school setup.",
    minPlan: "any",
    setupOwner: "platform",
    builtIn: true,
    docs: [
      { label: "Razorpay API reference", url: "https://razorpay.com/docs/api" },
      { label: "Webhooks", url: "https://razorpay.com/docs/payments/webhooks/" },
      { label: "Subscriptions API", url: "https://razorpay.com/docs/api/payments/subscriptions" },
    ],
    fields: [],
  },
  {
    id: "fcm-push",
    name: "Push notifications",
    vendor: "Firebase Cloud Messaging · built in",
    category: "communication",
    summary: "The mobile apps' notification channel.",
    whoPays: "Us — free tier",
    costModel: "included",
    costNote: "Already live, no per-school setup.",
    minPlan: "any",
    setupOwner: "platform",
    builtIn: true,
    docs: [
      { label: "HTTP v1 send API", url: "https://firebase.google.com/docs/cloud-messaging/send/v1-api" },
      { label: "projects.messages reference", url: "https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages" },
    ],
    fields: [],
  },
  {
    id: "s3-storage",
    name: "File storage",
    vendor: "S3-compatible bucket · built in",
    category: "storage",
    summary: "Documents, photos, result PDFs.",
    whoPays: "Us — storage + egress",
    costModel: "included",
    costNote: "Already live. Watch egress as photo-heavy schools join.",
    minPlan: "any",
    setupOwner: "platform",
    builtIn: true,
    docs: [
      { label: "S3 PutObject", url: "https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html" },
      { label: "S3 API operations index", url: "https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html" },
    ],
    fields: [],
  },
];

export const CONFIGURABLE_PROVIDERS = PROVIDERS.filter((p) => !p.builtIn);
export const OFFERED_PROVIDERS = CONFIGURABLE_PROVIDERS.filter((p) => p.offered !== false);
export const BUILT_IN_PROVIDERS = PROVIDERS.filter((p) => !!p.builtIn);

const BY_ID = new Map(PROVIDERS.map((p) => [p.id, p]));

export function getProvider(id: string): IntegrationProvider | undefined {
  return BY_ID.get(id);
}

export function planAllows(plan: PlanTier | null | undefined, minPlan: PlanTier | "any"): boolean {
  if (minPlan === "any") return true;
  if (!plan || !(plan in PLAN_ORDER)) return false;
  return PLAN_ORDER[plan] >= PLAN_ORDER[minPlan];
}

/**
 * "Not set up" and "needs upgrade" are derived, never stored: a row exists only once a
 * school starts connecting a provider.
 */
export function resolveStatus(
  plan: PlanTier | null | undefined,
  provider: IntegrationProvider,
  storedStatus?: string | null,
): ConnectionStatus {
  if (storedStatus === "connected" || storedStatus === "pending" || storedStatus === "error") {
    return storedStatus;
  }
  if (provider.builtIn) return "connected";
  if (provider.offered === false) return "not-offered";
  if (!planAllows(plan, provider.minPlan)) return "locked";
  return "available";
}

/** Field keys the API must encrypt before storage, and the ones it must never return. */
export function secretFieldKeys(provider: IntegrationProvider): string[] {
  return provider.fields.filter((f) => f.sensitive).map((f) => f.key);
}
